CC=clang
CC_ARGS=-Wall -Wextra -Wpedantic

build/main.o: main.c
	mkdir -p ./build
	$(CC) $(CC_ARGS) -o ./build/main.o -c main.c

build/program: build/main.o
	mkdir -p ./build
	$(CC) $(CC_ARGS) -o ./build/program ./build/main.o

run: build/program
	./build/program

build: build/program
